name: Server

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    env:
      working-directory: ./game-server
    permissions:
      id-token: write
      contents: read
      checks: write

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{ env.working-directory }}
    - name: Build
      run: dotnet build --no-restore
      working-directory: ${{ env.working-directory }}
    - name: Test
      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx" || true
      working-directory: ${{ env.working-directory }}
    - name: Test Report
      uses: dorny/test-reporter@v1
      with:
        name: DotNET Tests
        path: "**/test-results.trx"
        reporter: dotnet-trx
        fail-on-error: true
