name: Server

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    env:
      working-directory: ./game-server

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{ env.working-directory }}
    - name: Build
      run: dotnet build --no-restore --output ./output
      working-directory: ${{ env.working-directory }}
    - name: Test
      run: dotnet test --verbosity normal
      working-directory: ${{ env.working-directory }}
